server_ip: 10.1.11.31:7810
spring:
  profiles:
    active: prod
  application:
    name: hww-file-web-service-consumer
  data:
    jpa:
      repositories:
        enabled: true
#jpa
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:  
        dialect : org.hibernate.dialect.MySQLInnoDBDialect
      
#数据源    
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.11.32:3306/hww?characterEncoding=UTF-8&useSSL=true
    username: hww
    password: hww12#26%
    druid:
      initial-size: 20
      max-active: 40
      min-idle: 20
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
#      validation-query:
#      validation-query-timeout:
      #validationQuery:
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
#      time-between-eviction-runs-millis:
      min-evictable-idle-time-millis: 60000
      max-evictable-idle-time-millis: 300000
      filter:
         # 配置StatFilter
        stat:
          db-type: h2
          log-slow-sql: true
          slow-sql-millis: 2000
         # 配置WallFilter
        wall:
          enabled: true
          db-type: h2
          delete-allow: false
          drop-table-allow: false
#eureka
eureka:
  client:
    healthcheck: 
      enabled: true
    serviceUrl:
       defaultZone: http://10.1.11.36:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    #ip-address: 10.1.11.31
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  #配置instanceId显示IP