spring:
  profiles:
    active: dev
---
snowFlake: 
 datacenter_id: 1 #主键生成所属appid，注意一定不要重复 【0-31】
 cluster_id: 1 #主键生成所在  某应用下集群id， 所属应用的集群内 注意一定不要重复【0-31】
server:
  port: 7900
  session:
    timeout: 1800
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    max-connections: 800

#日志配置
logging:
  file: logs/hww-sys-web-service.log
  level:
    com.hww.sys: debug
