spring:
  profiles:
    active: prod
  application:
    name: hww-els-web-service-consumer 
eureka:
  client:
    healthcheck: 
      enabled: true
    serviceUrl:
       defaultZone: http://10.1.11.36:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    #ip-address: 10.1.11.23
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    
elastic.index.name: es_hww
elastic.cluster-name: haiwainet_hww
elastic.cluster-nodes: 10.1.11.107:9300,10.1.11.101:9300