spring: 
  profiles:
    active: dev
  application:
    name: hww-cms-web-service-consumer
    
snowFlake: 
 datacenter_id: 1 #主键生成所属datacenter_id，注意一定不要重复***** 【0-31】*****
 cluster_id: 1 #主键生成所在  某应用下集群id， 所属应用的集群内 注意一定不要重复【0-31】
 

  
server:
  port: 7809
  session:
    timeout: 1800
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    max-connections: 800
    
ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
hystrix:
  command: 
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
#日志配置
logging:
  file: logs/hww-cms-web-service.log
  level:
    com.hww.cms: debug
