
snowFlake: 
 datacenter_id: 1 #主键生成所属appid，注意一定不要重复 【0-31】
 cluster_id: 1 #主键生成所在  某应用下集群id， 所属应用的集群内 注意一定不要重复【0-31】
server:
  port: 7905
  session:
    timeout: 1800
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    max-connections: 800
  context-path: /appadmin
spring:
  profiles: 
    active: dev
  application:
    name: hww-app-web-admin
#模板配置
  freemarker:
    template-loader-path:
    - classpath:/template
    prefix: /app-view/
    suffix: .html
    content-type: text/html
    charset: UTF-8
    request-context-attribute: rc
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    
    settings:
      auto_import: /ftl/sys/index.ftl as p,/ftl/spring.ftl as s
      number_format : 0.##########
#  http:
#    multipart:
#      max-file-size: 1024000kb
  #自定义配置
custom:
  picUploadLocation: /upload/tmp/img/

#日志配置
logging:
  file: logs/hww-app-web-admin.log
  level:
    com.hww.app: debug